name: publish
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://debian:9
      env:
        EM_USE_GLOBAL_CACHE: 1

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: First step
        run: |
          apt update
          apt install cmake git make

          git clone --depth 1 --branch master --single-branch https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          source ./emsdk_env.sh
          cd ..

          ./run.sh
          rm build/web

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: test
          path: .
