name: publish
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: trzeci/emscripten-slim:latest
    with:
      env:
        EM_USE_GLOBAL_CACHE: 1

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: First step
        run: |
          # git clone -q --depth 1 --branch master --single-branch https://github.com/emscripten-core/emsdk.git
          # pushd .
          # cd emsdk
          # ./emsdk install latest
          # ./emsdk activate latest
          # source ./emsdk_env.sh
          # popd

          ./run.sh
          rm build/web

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: test
          path: .
