name: publish
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://alpine:edge
      env:
        EM_USE_GLOBAL_CACHE: 1

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: First step
        run: ./run.sh

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: test
          path: .
