name: publish
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://alpine:edge
      env:
        EM_USE_GLOBAL_CACHE: 1

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: First step
        run: |
          apk add -q cmake git make python tar xz

          git clone -q --depth 1 --branch master --single-branch https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
          export PATH=`pwd`:`pwd`/upstream/emscripten/:`echo node/*`/bin/:$PATH
          ls `pwd`
          ls `pwd`/upstream/emscripten/
          ls `echo node/*`/bin/
          cd ..

          echo $PATH

          ./run.sh
          rm build/web

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: test
          path: .
